### ISSUE TITLE
Stabilisation Roadmap

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#459]
StyLua is pretty stable now, with the formatting not changing wildly anymore. We should look to stabilise to something like `v2.0.0`

Stabilisation Guarantees:
- The formatting output is stable, and should not change excessively
- Major code formatting changes will be classified as a breaking change and will require a major version bump
- Minor version bumps will still allow minor style changes, especially around edge cases.
- With the above three points, a minor/patch version bump **should not** result in excessive diff noise

Checklist before stabilisation:
- [x] Runtime syntax selection support (`syntax = "Lua51"/"Lua52"/"Luau"`) [#103, #407]. This requires support upstream in full-moon
- [x] https://github.com/JohnnyMorganz/StyLua/issues/448
- [ ] Investigate ways to allow users to pin to an exact version of stylua easily in their tools (to prevent mismatching diffs - #398)
- [x] (Potentially) Lua 5.3 and Lua 5.4 support [#533, #534]. This requires support upstream in full-moon
- [x] Make stdin support respect-ignores flag: https://github.com/JohnnyMorganz/StyLua/pull/765
- [x] Remove legacy build artifacts (old names) from releases

... and a bit more as I continue to think on it. (All issues labelled as "bug" should also be resolved beforehand)

**Comment by JohnnyMorganz** [comment]
It is time :)

**Comment by chenrui333** [comment]
@JohnnyMorganz 👋 just curious, why not go with 1.0.0 before 2.0.0? :)

**Comment by JohnnyMorganz** [comment]
I didn't think v1 made much sense given StyLua has been in use for several years and across several versions now: v1 almost indicates to me it's the "initial release" of the project

**Comment by chenrui333** [comment]
cool, thanks for confirming it. 👍
